// <auto-generated />
namespace ApiServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class not_null_ship_status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(not_null_ship_status));
        
        string IMigrationMetadata.Id
        {
            get { return "201512060249478_not_null_ship_status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
